version: "3.8"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__WEBSERVER__SECRET_KEY: "airflow-secret"
    PYTHONPATH: /opt/airflow
  volumes:
    - ./:/opt/airflow
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username airflow --firstname Air --lastname Flow --role Admin --email admin@example.com --password airflow || true"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler