FROM apache/airflow:2.10.5-python3.11

USER airflow

COPY requirements.txt /requirements.txt
COPY requirements.airflow.txt /requirements.airflow.txt
RUN pip install --no-cache-dir -r /requirements.airflow.txt \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-3.11.txt"